tap "homebrew/bundle"
brew "mas"
brew "asdf"
brew "difftastic"
brew "fzf"
brew "kubernetes-cli"
brew "kube-ps1"
brew "macvim"
brew "ripgrep"
brew "speedtest-cli"
brew "stow"
brew "thefuck"
brew "yq"
cask "1password-cli"
cask "google-cloud-sdk"

tap "zackelia/formulae"
brew "bclm"

mas "Amphetamine", id: 937984704
